/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Dispatch, SetStateAction, useEffect, useState } from "react";

import { useGLTF } from "@react-three/drei";
import { Euler, Vector3 } from "three";
import { degreeToRadian } from "@/utils";

interface OneHundredThousandProps {
  scale: number;
  position: Vector3;
  setTarget: Dispatch<SetStateAction<Vector3>>;
}

export function OneHundredThousand(props: OneHundredThousandProps) {
  const model: any = useGLTF("/one_hundred_thousand/one_hundred_thousand.glb");
  const nodes = model.nodes;
  const materials = model.materials;
  const { setTarget } = props;
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    document.body.style.cursor = hovered ? "pointer" : "auto";

    return () => {
      document.body.style.cursor = "auto";
    };
  }, [hovered]);
  return (
    <group
      scale={props.scale}
      position={props.position}
      dispose={null}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
      rotation={new Euler(0, degreeToRadian(-15), 0)}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material1.geometry}
        material={materials["00000dollar"]}
        onDoubleClick={(e) => {
          setTarget(e.intersections[0].point.clone());
        }}
      />
    </group>
  );
}

useGLTF.preload("/one_hundred_thousand/one_hundred_thousand.glb");
