/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useState } from "react";

import { useGLTF } from "@react-three/drei";

export function OneHundredThousand(props: any) {
  const { nodes, materials } = useGLTF(
    "/one_hundred_thousand/one_hundred_thousand.glb"
  );
  const { setTarget } = props;
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    document.body.style.cursor = hovered ? "pointer" : "auto";

    return () => {
      document.body.style.cursor = "auto";
    };
  }, [hovered]);
  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material1.geometry}
        material={materials["00000dollar"]}
        onDoubleClick={(e) => {
          setTarget(e.intersections[0].point.clone());
        }}
      />
    </group>
  );
}

useGLTF.preload("/one_hundred_thousand/one_hundred_thousand.glb");
