/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { Dispatch, SetStateAction, useEffect, useState } from "react";
import { Vector3 } from "three";

import { useGLTF } from "@react-three/drei";

interface TenGrandProps {
  position: Vector3;
  scale: number;
  setTarget: Dispatch<SetStateAction<Vector3>>;
}

export function TenGrand(props: TenGrandProps) {
  const model: any = useGLTF("/all_bills/scene.glb");
  const nodes = model.nodes;
  const materials = model.materials;
  const { setTarget } = props;
  const [hovered, setHovered] = useState(false);

  useEffect(() => {
    document.body.style.cursor = hovered ? "pointer" : "auto";

    return () => {
      document.body.style.cursor = "auto";
    };
  }, [hovered]);

  return (
    <group
      {...props}
      dispose={null}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <group rotation={[Math.PI / 2, 0, -Math.PI]}>
        <group rotation={[-Math.PI, 0, 0]} scale={1}>
          <group rotation={[0, 0, 3.14]} scale={[7, 6.63, 100]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.StackOf100Dollars_BantMat_0.geometry}
              material={materials.BantMat}
              onDoubleClick={(e) => {
                setTarget(e.intersections[0].point.clone());
              }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.StackOf100Dollars_Numbers_Mat_0.geometry}
              material={materials.Numbers_Mat}
              onDoubleClick={(e) => {
                setTarget(e.intersections[0].point.clone());
              }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.StackOf100Dollars_100DFront_Mat_0.geometry}
              material={materials["100DFront_Mat"]}
              onDoubleClick={(e) => {
                setTarget(e.intersections[0].point.clone());
              }}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.StackOf100Dollars_100DBack_Mat_0.geometry}
              material={materials["100DBack_Mat"]}
              onDoubleClick={(e) => {
                setTarget(e.intersections[0].point.clone());
              }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/all_bills/scene.glb");
